# Documentation
# https://docs.docker.com/compose/compose-file

version: "3"

services:
  eventstore:
    image: eventstore/eventstore:21.6.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'

  api:
    image: node:17-alpine
    working_dir: /app
    # command: yarn start:dev
    depends_on:
      - eventstore
    # env_file: .env
    environment:
      - EVENT_STORE_HOSTNAME=eventstore
    ports:
      - 7070:7070
    volumes:
      - ./api/:/app/
    stdin_open: true
